### ISSUE TITLE
CMOVZ sequence not fully optimised

### ISSUE THREAD

**Issue by jonwoodruff** [CTSRD-CHERI/llvm-project#291]
Building this:
"
int * __capability test(int * __capability inCap, int test, int inInt)
{
  int * __capability ret = inCap;
  if (test) {
    ret = (int * __capability) inInt;
  }
  return ret;
} 
"
Yields this:
"
	cfromptr	$c1, $c0, $5
	ccmovz	$c1, $c3, $4
	cmove	$c3,  $c1
"
But should yield something like this:
"
	cfromptr	$c1, $c0, $5
	ccmovn	$c3, $c1, $4
"
Maybe CCMOVN isn't supported yet?

**Comment by arichardson** [comment]
Code looks reasonable now: https://cheri-compiler-explorer.cl.cam.ac.uk/z/dK3qMY

**Comment by arichardson** [comment]
Well it could be improved but it matches MIPS so there is no point fixing it.
