### ISSUE TITLE
.cpsetup and .cprestore don't understand CheriABI stacks

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm-project#307]
The .cpsetup and .cprestore macros attempt to load and store gp via `ld`, `sd` instructions on `sp`.  They should be taught to access the stack via `$c11` and `sp`.

In practice, we don't seem to generate assembly that uses `gp` so this hasn't provided important since it's callee save.

**Comment by arichardson** [comment]
Do we still need `.cpsetup` for CheriABI?

**Comment by arichardson** [comment]
Closing as WONTFIX. We don't need .cpsetup/.cprestore and I considering that MIPS support is going away there is no point adding a new warning to the MIPS assembler.
