### ISSUE TITLE
BERI1 supports the MIPS III ISA, not MIPS IV

### ISSUE THREAD

**Issue by michael-roe** [CTSRD-CHERI/llvm-project#308]
BERI1 was written to be compatible with the MIPS III ISA. It supports enough extensions that integer-only MIPS IV code will (probably) work, but floating point definitely won't work (because, for example, BERI1 doesn't support MADD.fmt)

But the LLVM backend generates MIPS IV code for cheri. We probably ought to support a -mcpu=mips3 option (or something similar) to force generation of MIPS III code when needed.

There is a conceptual difference between the CHERI ISA and its implementations (in CHERI1, CHERI2, the L3 formal model, etc) so that in principle the CHERI ISA does not necessarily imply the MIPS III ISA.  CHERI+MIPS IV makes sense in principle, but no-one has implemented it yet. For this reason, I'd suggest a -mcpu=mips3 option rather than hard-coding mips3.

**Comment by arichardson** [comment]
Is this still broken?

**Comment by michael-roe** [comment]
I believe this is worked around -- we fixed LLVM so that is doesn't use the
MIPS-IV  multiply and add (madd) instruction that BERI doesn't have.
