### ISSUE TITLE
Hybrid and MIPS code has different stack alignment

### ISSUE THREAD

**Issue by trasz** [CTSRD-CHERI/llvm-project#312]
For hybrid CHERI-256 code, the stack alignment is 32 bytes.  For MIPS - 16.  This causes obvious problems when linking object files compiled with both: hybrid function called from MIPS one will get alignment faults for objects on the stack.

This prevents selective compilation of selected kernel source files as hybrid.

What do to about it?  Default to 32 bytes in all cases, perhaps?

**Comment by bsdjhb** [comment]
I think we can close this.  We currently compile CheriBSD with -mstack-alignment=32 for 256.  For 128, the 16 byte alignment already works.  I doubt anyone will implement -mrealign-stack for MIPS.
