### ISSUE TITLE
Value of __UINTPTR_MAX__ is not useful

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/llvm-project#316]
Currently it expands to (2<<CAP_SIZE -1). This is not useful for anything since we can have integer types with such a large value.

Option 1) Make it expand to maximum integer value that can be stored in the offset field of a capability
But that might allow code that uses `__UINTPTR_MAX__ == __UINT64_MAX__` to assume that pointers are 64 bits

Option 2) Make any use of `__UINTPTR_MAX__` a compiler error since the maximum integer value of a pointer is not a useful concept in any way.

Option 3) Do nothing an assume that `#define __UINTPTR_MAX__ 340282366920938463463374607431768211455` will not allow any existing code to compile.

**Comment by jrtc27** [comment]
> Option 1) Make it expand to maximum integer value that can be stored in the offset field of a capability
> But that might allow code that uses `__UINTPTR_MAX__ == __UINT64_MAX__` to assume that pointers are 64 bits

This matches `__UINTCAP_MAX__` and I think is the only option that makes sense.

> Option 2) Make any use of `__UINTPTR_MAX__` a compiler error since the maximum integer value of a pointer is not a useful concept in any way.

The existence of `uintptr_t` is optional (C11 §7.20.1.4), and whilst not explicitly stated, I imagine the intent is that `UINTPTR_MAX` is required if the type is present (as-is, the standard reads as if the macro is always required no matter what). I don't think we should deviate from the standard more than we have to.

> Option 3) Do nothing an assume that `#define __UINTPTR_MAX__ 340282366920938463463374607431768211455` will not allow any existing code to compile.

Other than requiring no changes to Clang, this doesn't really get you anywhere, it's just option 2 in disguise.

So, personally, I'm of the view that we should do option 1.
