### ISSUE TITLE
Clang crashes when used with source annotations.

### ISSUE THREAD

**Issue by kwitaszczyk** [CTSRD-CHERI/llvm-project#325]
When using Clang with source annotations, I encountered a strange bug. With an example anonymous structure definition:
```
struct {
    int u;
    __attribute__((annotate("myannotation"))) int v;
} var;
```
Clang crashes when `v` is assigned a value, `u` is not assigned a value and a program is compiled with the pure-capability ABI.

A preprocessed example source file that can be used to reproduce this problem can be found here: https://gist.github.com/kwitaszczyk/09ca9f6f17b62f2c2c2a337c0d3d5c28 .

A run script produced by Clang for the case the compiler fails can be found here:
https://gist.github.com/kwitaszczyk/589bed52f3ff0dfe1a035f516f4fc23e .

An example output with a crash backtrace presenting the crash can be found here: https://gist.github.com/kwitaszczyk/db45dedcddba01da171bfe815aede72f . The output also shows that the source file compiles correctly when:
* The file is compiled with the pure-capability ABI and none fields are assigned values;
* The file is compiled with the pure-capability ABI and only `u` is assigned a value;
* The file is compiled with the pure-capability ABI and both `u`, `v` are assigned values;
* The file is compiled with the pure-capability ABI, the annotation is removed and `v` is assigned a value;
* The file is compiled with the hybrid ABI and only `v` is assigned a value.

Unfortunately I haven't managed to fix this bug. Could you tell if you have the same problem with source annotations and if you have any ideas how to fix it?

**Comment by arichardson** [comment]
Thanks for the report. I can reproduce it with the following minimal test:
```
// RUN: %cheri_purecap_cc1 -o - -emit-llvm -O0 %s
void a(void) {
  __attribute__((annotate("foo"))) int b;
}
```

**Comment by kwitaszczyk** [comment]
@arichardson Thank you for solving this issue! I confirm that the problem doesn't occur anymore.

I've reported a similar issue when source annotations are used with capabilities: #327.
