### ISSUE TITLE
Incorrect "control flow readhes end of non-void function"

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/llvm-project#331]
A follow-up to #330.  The following...

```
  template<size_t granule, typename T = void>
  inline T* pointer_align_down(void* p)
  {
    static_assert(granule > 0);
    static_assert((granule & (granule - 1)) == 0);
    return reinterpret_cast<T*>(__builtin_align_down(p, granule));
  }
```

trips "error: control reaches end of non-void function [-Werror,-Wreturn-type]".  I think somebody's quite confused (other than me, I mean).

**Comment by arichardson** [comment]
Hmm is this still happening after the latest commit?

**Comment by nwf** [comment]
My bad for being behind!  Thanks!
