### ISSUE TITLE
Subobject setbounds reordered before conditional check, causing crash

### ISSUE THREAD

**Issue by qwattash** [CTSRD-CHERI/llvm-project#359]
This happens in the multicast network layer, triggered by the inet6 subsystem.

In [`net/if.c`](https://github.com/CTSRD-CHERI/cheribsd/blob/d3ac50607cf0673aea6ac4aa69bfda7cfffd3b1a/sys/net/if.c#L3827-L3845) the function `if_findmulti(struct ifnet *ifp, const struct sockaddr *sa)`, the `sa_dl_equal` check uses the [`struct sockaddr_dl.sdl_data`](https://github.com/CTSRD-CHERI/cheribsd/blob/d3ac50607cf0673aea6ac4aa69bfda7cfffd3b1a/sys/net/if_dl.h#L59-L69) field via the `CLLADDR` macro. This triggers the sdl_data bounds to be enforced on the `sa` pointer. The csetbounds for this is reordered before the `sa->sa_family` check, causing a length violation for non AF_LINK addresses.

This may be related to #348.

**Comment by arichardson** [comment]
Should be fixed by https://github.com/CTSRD-CHERI/llvm-project/pull/462
