### ISSUE TITLE
compiler crash with assignment of reference to array element

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm-project#363]
```
// RUN: %cheri_cc1 -o - -emit-llvm -O0 -Wimplicit-int  -Wfatal-errors %s
struct a b;
short c;
int *d;
struct a {
  int *__attribute__((cheri_capability)) e
} f() {
  d = &b.e[c];
}
```

In the actual code the issue was:
```
struct sem *semptr = NULL;
semptr = &semakptr->u.__sem_base[sopptr->sem_num];
```
where the `__sem_base` member is a `struct sem * __capability`.  Changing `semptr` to have an `__capability` annotation caused the compiler to stop crashing.

**Comment by arichardson** [comment]
Looks like clang needs to either emit an error here or insert an implicit cast expression. I would lean towards making this an error an requiring a `__cheri_tocap` cast?

**Comment by brooksdavis** [comment]
Making it an error is fine by me.
