### ISSUE TITLE
RISC-V purecap crashes with __builtin_return_address( 0 )

### ISSUE THREAD

**Issue by heshamelmatary** [CTSRD-CHERI/llvm-project#384]

**Comment by arichardson** [comment]
This works now. https://github.com/CTSRD-CHERI/llvm-project/commit/a8e80061caf96c68f0f6f488e66499956cc7a466 and https://github.com/CTSRD-CHERI/llvm-project/commit/4dde4dfac83b88e1ad02aabc127b23101ca739cc seem like likely fixes.
