### ISSUE TITLE
fatal error: error in backend: Cannot select: intrinsic %llvm.cheri.cap.perms.check

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/llvm-project#430]
reproducer: https://gist.github.com/brooksdavis/f2645744505291f5f835b7f86bc696d2

**Comment by arichardson** [comment]
We should probably just remove those instructions since they aren't useful.

**Comment by jrtc27** [comment]
Not a bug; the instruction was left behind with CHERI-MIPS so it's expected that the intrinsic can't be selected.
