### ISSUE TITLE
Hybrid mode should realign the stack for capability allocas

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/llvm-project#431]
If the only user of an alloca is a cast from integer pointer to capability pointer, we should increase the alignment of the alloca to ensure precisely representable bounds:

Example:
```c
#include <stddef.h>
void test_bounds_precise(void* __capability cap, size_t len);


void test_bounds_stack_alloca(size_t len)
{
	void * __capability c = (__cheri_tocap void * __capability)alloca(len);

	test_bounds_precise(c, len);
}

void test_64k(void) {
    test_bounds_stack_alloca(65536);
}
```

**Comment by jrtc27** [comment]
Well, I think it should be if _any_ user is such a cast. The only reasons not to do it are 1) wasted stack space 2) lack of CRRL/CRAM.

**Comment by brooksdavis** [comment]
Given we're moving away from bounding objects in hybrid mode (#647), I think may want to close this issue.

**Comment by jrtc27** [comment]
We might want something like this for the hypothetical `__capability &stack_var`, which would always bound, but yeah as it stands we don't want this.

**Comment by jrtc27** [comment]
Certainly not a "good first issue" we should be directing people towards...
