### ISSUE TITLE
Cannot select capability-authorized AtomicLoadOr

### ISSUE THREAD

**Issue by nwf** [CTSRD-CHERI/llvm-project#470]
I suspect this is a known gap in our instruction set (IIRC we don't yet have cap-authorized AMOs?) but maybe it could be transformed out to a loop around `CLoadResCap`+`CStoreCondCap`?

Reduced test case follows, though really just attempting to use `atomic_fetch_or_explicit` from C will trigger it.

```
; RUN: %clang_cc1 -triple riscv64-unknown-freebsd13.0 -emit-obj -disable-free -mrelocation-model static -mframe-pointer=none -fno-rounding-math -mconstructor-aliases -munwind-tables -target-feature +m -target-feature +a -target-feature +f -target-feature +d -target-feature +c -target-feature +xcheri -target-feature -save-restore -target-feature -relax -target-abi lp64d -msmall-data-limit 8 -fno-split-dwarf-inlining -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=gdb -nobuiltininc -O2 -fconst-strings -ferror-limit 19 -stack-protector 2 -fno-signed-char -fgnuc-version=4.2.1 -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -o - -x ir %s
; ModuleID = '/tmp/libcheri_caprevoke-3b6bb3-bugpoint-reduce.ll-reduced-simplified.bc'
source_filename = "/tmp/libcheri_caprevoke-3b6bb3.c"
target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n64-S128"
target triple = "riscv64-unknown-freebsd13.0"

define dso_local void @snork() #0 {
bb:
  br i1 undef, label %bb1, label %bb2

bb1:                                              ; preds = %bb
  ret void

bb2:                                              ; preds = %bb
  %tmp = atomicrmw or i64 addrspace(200)* undef, i64 undef monotonic
  br label %bb3

bb3:                                              ; preds = %bb3, %bb2
  br label %bb3
}

attributes #0 = { "use-soft-float"="false" }

!llvm.ident = !{!0}

!0 = !{!"clang version 11.0.0 (https://github.com/CTSRD-CHERI/llvm-project.git ff2ddd432e78b344c2c5178d9ac27143f6085d6b)"}
```

**Comment by jrtc27** [comment]
Yeah, the lack of RMW support for capabilities is known, IIRC Alex has said that LLVM and/or Clang just aren't set up for the two operands being different types. It does need to be addressed eventually, but it's not high priority. I assume this is equally unhappy on MIPS?

**Comment by nwf** [comment]
Amusingly, no, it just works on MIPS, which is why I only noticed now.  The same line in `libcheri_caprevoke.c` (that is, an `atomic_fetch_or_explicit`) compiles down on MIPS as might be expected:

```
     558: 4a 01 90 0b   clld    $1, $c18
     55c: 00 22 18 25   or      $3, $1, $2
     560: 4a 03 90 c3   cscd    $3, $3, $c18
     564: 10 60 ff fc   beqz    $3, -12 <caprev_shadow_nomap_set_len+0x128>
     568: 00 00 00 00   nop <caprev_shadow_nomap_offsets>
```

**Comment by arichardson** [comment]
This is quite odd, I'd expect i64 rmw ops to work in purecap. Capability rmw atomics other than xchg are known to be broken but this should definitely work.

**Comment by arichardson** [comment]
Aha it's not purecap. That explains the failure. I guess we should convert it to lr sc?

**Comment by jrtc27** [comment]
Oh. Yeah I haven't implemented cross-mode atomics on RISC-V, that's yet more combinatorial explosion in the pseudo-instruction expansion pass, though maybe not too bad, just a bit of extra state to pass around and mostly limited to the getLR/SC* helpers. I suggest you either punt on hybrid for now or write the inline assembly yourself.

**Comment by jrtc27** [comment]
(I mistakenly thought this was atomics on capabilities, not atomics with capabilities)
