### ISSUE TITLE
Fix symbol preemption for call site landing pads

### ISSUE THREAD

**Issue by jrtc27** [CTSRD-CHERI/llvm-project#512]
Currently landing pads use:
```
.chericap foo + .Ltmp - .Lfunc_begin
```
(where `foo` is the function name, `.Ltmp` is a label at the landing pad and `.Lfunc_begin` is a non-preemptible label at the same location as `foo`)
This means we use the preemptible symbol which is (a) more expensive as it has to be preserved through to run time (b) wrong in the case it actually gets preempted (in practice the landing pad is unlikely to be needed as the function itself won't be called, but -Bsymbolic and -fno-semantic-interposition can result in such situations arising).

Fixing this will require:
1. Emitting type + size information for the `.Lfunc_begin` symbols
2. Using them in place of the preemptible function symbol

NB: We should also check we emit type + size information for the `.Lfoo$local` symbols used with -fno-semantic-interposition

**Comment by arichardson** [comment]
Turns out there is an ugly hack in lld that adds `__cheri_eh_$NAME` aliases. Should probably retire that.
