### ISSUE TITLE
Parsing fails in hybrid C on linebreak between struct name and __capability

### ISSUE THREAD

**Issue by kevin-brodsky-arm** [CTSRD-CHERI/llvm-project#606]
For some really strange reason, in hybrid C, Clang gets extremely confused if a linebreak is introduced between `struct foo` and `__capability` (in the legacy prefix position) in a cast expression like `(struct foo __capability *)`.

Minimal reproducer [here](https://cheri-compiler-explorer.cl.cam.ac.uk/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,selection:(endColumn:30,endLineNumber:7,positionColumn:30,positionLineNumber:7,selectionStartColumn:30,selectionStartLineNumber:7,startColumn:30,startLineNumber:7),source:'struct+s+%7B%0A++++int+i%3B%0A%7D%3B%0A%0Astruct+s+*+__capability+foo(void+*+__capability+x)+%7B%0A++++return+(struct+s+%0A++++++++++++__capability+*)x%3B%0A%7D'),l:'5',n:'0',o:'C+source+%231',t:'0')),k:50.24223119813004,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:cheri-riscv64-hybrid,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:___c,libs:!(),options:'-O2+-Wno-deprecated-declarations',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1,tree:'1'),l:'5',n:'0',o:'Hybrid+CHERI-RISCV64+(C,+Editor+%231,+Compiler+%231)',t:'0')),k:32.32874191015375,l:'4',m:50,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,fontUsePx:'0',tree:'1',wrap:'1'),l:'5',n:'0',o:'Output+of+Hybrid+CHERI-RISCV64+(Compiler+%231)',t:'0')),header:(),l:'4',m:50,n:'0',o:'',s:0,t:'0')),k:49.75776880186997,l:'3',n:'0',o:'',t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

**Comment by brooksdavis** [comment]
That's really weird. I guess we never hit it before because line breaks in casts are such an obvious abomination. :)

**Comment by kevin-brodsky-arm** [comment]
I guess Linux drivers do provide a good coverage of "unusual" coding styles ;) https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/tty/vt/vt.c?h=v5.15#n3200

**Comment by kevin-brodsky-arm** [comment]
Fixed by 60af8cd.
