### ISSUE TITLE
Using a non-capability register in riscv inline assembly where a capability register is expected causes llvm termination

### ISSUE THREAD

**Issue by NickLewisL3H** [CTSRD-CHERI/llvm-project#678]
Using a non-capability register in riscv inline assembly where a capability register is expected causes llvm termination. There is no information to the user on the line of source code that caused the termination. As well as the location of the source it would be useful if the identity of the register at fault were also provided to the user.

**Comment by NickLewisL3H** [comment]
The following example code:

`void crashme() {
    register void * tmp1 asm("t1");
    register long tmp2 asm("ct2");
    register long tmp3 asm("ct3");
    asm ("" : "=r"(tmp1), "=r"(tmp2));
    asm ("" : "=r"(tmp3));
}
`
results in:

`fatal error: error in backend: Unknown mismatch in getCopyFromParts!`

**Comment by NickLewisL3H** [comment]
With the following suggested change:

`@@ -303,7 +306,25 @@ static SDValue getCopyFromParts(SelectionDAG &DAG, const SDLoc &DL,
     return DAG.getNode(ISD::TRUNCATE, DL, ValueVT, Val);
   }
 
-  report_fatal_error("Unknown mismatch in getCopyFromParts!");
+  const char* RegName = "";
+  const char* RegLabel = "";
+  if (Reg) {
+      const MachineFunction &MF = DAG.getMachineFunction();
+      const TargetRegisterInfo &TRI = *MF.getSubtarget().getRegisterInfo();
+      RegName = TRI.getName(Reg);
+      RegLabel = " for register ";
+  }
+
+  if (PartEVT.isFatPointer() || ValueVT.isFatPointer()) {
+     diagnosePossiblyInvalidConstraint(
+         *DAG.getContext(), V, "unsupported capability conversion" +
+         Twine(RegLabel) + Twine(RegName));
+     return DAG.getUNDEF(ValueVT);
+  }
+
+  report_fatal_error("Unknown mismatch in getCopyFromParts: " +
+                     PartEVT.getEVTString() + " vs " + ValueVT.getEVTString() +
+                     RegLabel + RegName);
 }
 
 static void diagnosePossiblyInvalidConstraint(LLVMContext &Ctx, const Value *V,
`
the error is a more user friendly:

`example.c:5:10: error: unsupported capability conversion for register X6, possible invalid constraint
    asm ("" : "=r"(tmp1), "=r"(tmp2));
         ^
example.c:5:10: error: unsupported capability conversion for register C7, possible invalid constraint
example.c:6:10: error: unsupported capability conversion for register C28, possible invalid constraint
    asm ("" : "=r"(tmp3));
         ^
3 errors generated.
`

**Comment by jrtc27** [comment]
It works for your case but isn't the right fix. If it's going to be diagnosed it should be done so at a higher level, getCopyFromParts isn't meant to fail. Note also that getCopyFromParts is used for a huge variety of things, not just inline assembly.

**Comment by NickLewisL3H** [comment]
it looks like getCopyFromParts (and getCopyToParts) is also failing on some "vectors" which is from where i borrowed the diagnosePossiblyInvalidConstraint cludge. i accept it isnt nice despite being more user friendly.

Is it correct to assume that getCopyFromParts should never be asked to convert to or from a capability? Is such a mismatch an inline asm error by the user that should be explicitly checked for and blocked beforehand?

**Comment by jrtc27** [comment]
Duplicates #373 (other side)
