### ISSUE TITLE
Can not run clang on cheribsd-riscv64-purecap

### ISSUE THREAD

**Issue by zintown** [CTSRD-CHERI/llvm-project#699]
I have installed llvm-riscv64-hybrid-for-purecap-rootfs by cheribuild.py, but when I run clang on cheribsd-riscv64-purecap, it failed.
the command is:
```
/opt/riscv64-hybrid/llvm-project/bin/clang-14
```
the error message is:
```
Warning: Attempted to load position-dependent executable with non-representable base: /opt/riscv64-hybrid/llvm-project/bin/clang-14
Abort trap
```
Where is the problem? 
Do I need to add specific compilation options when compiling llvm-riscv64-hybrid-for-purecap-rootfs？

**Comment by jrtc27** [comment]
Fixed by https://github.com/CTSRD-CHERI/cheribsd/pull/1741
